"""Create messages table

Revision ID: 46411050b925
Revises: f74517207462
Create Date: 2024-10-05 02:55:49.532986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46411050b925'
down_revision = 'f74517207462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_', sa.Integer(), nullable=False),
    sa.Column('to_', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('timestanp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
